---
# web server installation
- hosts: webserver
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: latest
    - name: Copy remote file
        shell: scp sistemasdistribuidos@192.168.130.198:/home/sistemasdistribuidos/Documentos/html /var/www/html


        #database installation
#- hosts: database
#  become: yes
#  become_user: root
#  become_method: sudo
#  tasks:
#    - name: install apache2
#      apt:
#        name: apache2
#        state: latest
    
    
